# Generated by Django 5.0.1 on 2024-01-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_userprofile_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_address',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
    ]
